 FROM python:2.7-slim

 RUN mkdir /app
 WORKDIR /app

 COPY requirements.txt requirements.txt
 RUN pip install -r requirements.txt

 COPY . .

 LABEL maintainer="Parisa Moosavinezhad <parisamoosavinezhad@yahoo.com>" \
 version="1.0"

 #CMD Flask run --host=0.0.0.0 --port=80

 # Make port 80 available to the world outside this container
 #EXPOSE 80

 # Define environment variable
 #ENV NAME World

 # Run app.py when the container launches
 CMD ["python", "app.py"]