// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4, iterations: "1000" };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "anonymiseEntry",
    id: "72af85a5-e5e6-4a10-b4d8-e11524cbaa44",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <anonymiseEntry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <value xmlns="">sta_069098490</value>\r\n      <domainName xmlns="">test</domainName>\r\n    </anonymiseEntry>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "deleteEntries",
    id: "df3d796f-4a98-4c1c-9b8a-25bfe243b04e",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <deleteEntries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <values xmlns="">values1</values>\r\n      <domainName xmlns="">domainName1</domainName>\r\n    </deleteEntries>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "deleteEntry",
    id: "3669b5e8-0a77-4f14-a3da-1ecd8ce14ecb",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <deleteEntry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <value xmlns="">sta_069098490</value>\r\n      <domainName xmlns="">my test</domainName>\r\n    </deleteEntry>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getOrCreatePseudonymFor",
    id: "8701a10d-e473-4680-a835-bc2b012ff4a2",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getOrCreatePseudonymFor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <value xmlns="">pri_100003928</value>\r\n      <domainName xmlns="">test</domainName>\r\n    </getOrCreatePseudonymFor>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getOrCreatePseudonymForList",
    id: "bc7f444c-ab97-485b-83a8-652afd8e60cf",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getOrCreatePseudonymForList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      {{text}}\r\n      <domainName xmlns="">test</domainName>\r\n    </getOrCreatePseudonymForList>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    pre() {
      var samplecount = 49999;
      var min = 10000000;
      var max = 999999999;
      var i;
      var text = "";
      var random = Math.floor(Math.random() * (max - min)) + min;
      random = "pri_" + random.toString();

      for (i = 1; i <= samplecount; i++) {
        var random = Math.floor(Math.random() * (max - min)) + min;
        random = "pri_" + random.toString();
        text += "<values xmlns=''>" + random + "</values>";
      }

      pm.globals.set("text", text);
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getPseudonymFor",
    id: "c7789951-fbbb-4298-b10c-78e7fc659687",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getPseudonymFor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <value xmlns="">sta_069098478</value>\r\n      <domainName xmlns="">Forscher 2</domainName>\r\n    </getPseudonymFor>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getPseudonymForList",
    id: "6a27fc59-ae0d-402a-bf8a-2cd2bf1a39f2",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getPseudonymForList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <values xmlns="">values1</values>\r\n      <domainName xmlns="">domainName1</domainName>\r\n    </getPseudonymForList>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getPseudonymForValuePrefix",
    id: "7f0bdbe0-b8f3-4a8b-8f9d-7b92c834fa97",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getPseudonymForValuePrefix xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <valuePrefix xmlns="">valuePrefix1</valuePrefix>\r\n      <domainName xmlns="">domainName1</domainName>\r\n    </getPseudonymForValuePrefix>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getPSNNetFor",
    id: "98dfb7b1-296a-4823-bdbe-0906fbee2a3e",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getPSNNetFor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <valueOrPSN xmlns="">psn_746616974</valueOrPSN>\r\n    </getPSNNetFor>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getPSNTreeForPSN",
    id: "95cf8410-6746-4baf-b655-b6f51e291a27",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getPSNTreeForPSN xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <psn xmlns="">psn1</psn>\r\n      <domainName xmlns="">domainName1</domainName>\r\n    </getPSNTreeForPSN>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getValueFor",
    id: "89f8dc09-26f4-412e-ae2f-4395d63fe83e",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getValueFor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <psn xmlns="">f2_150736471</psn>\r\n      <domainName xmlns="">Forscher 2</domainName>\r\n    </getValueFor>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "getValueForList",
    id: "35045581-f78b-4812-9e9e-bc5d99ad9127",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <getValueForList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <psnList xmlns="">psn_02641823310</psnList>\r\n      <psnList xmlns="">psn_27079326410</psnList>\r\n      <domainName xmlns="">my test</domainName>\r\n    </getValueForList>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "insertValuePseudonymPair",
    id: "1d77f43e-53d5-40d6-863f-cce8edbc6d05",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <insertValuePseudonymPair xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <value xmlns="">sta_069098491</value>\r\n      <pseudonym xmlns="">psn_60900941911</pseudonym>\r\n      <domainName xmlns="">my test</domainName>\r\n    </insertValuePseudonymPair>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "insertValuePseudonymPairs",
    id: "8963a83b-6a44-4c33-8226-ab00165a8b0c",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <insertValuePseudonymPairs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <pairs xmlns="">\r\n        <entry>\r\n          <key>key1</key>\r\n          <value>value1</value>\r\n        </entry>\r\n        <entry>\r\n          <key>key2</key>\r\n          <value>value2</value>\r\n        </entry>\r\n        <entry>\r\n          <key>key3</key>\r\n          <value>value3</value>\r\n        </entry>\r\n        <entry>\r\n          <key>key4</key>\r\n          <value>value4</value>\r\n        </entry>\r\n        <entry>\r\n          <key>key5</key>\r\n          <value>value5</value>\r\n        </entry>\r\n      </pairs>\r\n      <domainName xmlns="">domainName1</domainName>\r\n    </insertValuePseudonymPairs>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "validatePSN",
    id: "8ad48d8d-a8fd-459a-bafa-3f68af08abbe",
    method: "POST",
    address: "http://localhost:8080/gpas/gpasService",
    data:
      '<?xml version="1.0" encoding="utf-8"?>\r\n<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">\r\n  <Body>\r\n    <validatePSN xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://psn.ttp.ganimed.icmvc.emau.org/">\r\n      <psn xmlns="">pdn_746616974</psn>\r\n      <domainName xmlns="">test</domainName>\r\n    </validatePSN>\r\n  </Body>\r\n</Envelope>',
    headers: {
      "Content-Type": "text/xml"
    },
    post(response) {
      pm.test("Status test", function() {
        pm.response.to.have.status(200);
      });
    }
  });
}
