 FROM python:2.7-alpine

 RUN mkdir /app
 WORKDIR /app

 COPY requirements.txt requirements.txt
 RUN pip install -r requirements.txt

 COPY . .

 LABEL maintainer="Parisa Moosavinezhad <parisamoosavinezhad@yahoo.com>"

 #CMD Flask run --host=0.0.0.0 --port=5000

 # Make port 80 available to the world outside this container
 #EXPOSE 80

 # Define environment variable
 #ENV NAME World

 # Run app.py when the container launches
 CMD ["python", "app.py"]